sudo: false
dist: trusty
language: cpp
python:
  - "2.7"

matrix:
  include:

    - env: CC_COMPILER="./test/wasm-install/wasm-install/bin/clang" CXX_COMPILER="./test/wasm-install/wasm-install/bin/clang++"
      compiler: clang
      addons: &stuff
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['cmake', 'nodejs', 'libstdc++-4.8-dev']

    - env: CC_COMPILER="./test/wasm-install/wasm-install/bin/clang" CXX_COMPILER="./test/wasm-install/wasm-install/bin/clang++" COMPILER_FLAGS="-fsanitize=undefined -fno-sanitize-recover=all -fsanitize-blacklist=`pwd`/ubsan.blacklist"
      compiler: clang
      addons: *stuff

    - env: CC_COMPILER="./test/wasm-install/wasm-install/bin/clang" CXX_COMPILER="./test/wasm-install/wasm-install/bin/clang++" COMPILER_FLAGS="-fsanitize=address"
      compiler: clang
      addons: *stuff

    - env: CC_COMPILER="./test/wasm-install/wasm-install/bin/clang" CXX_COMPILER="./test/wasm-install/wasm-install/bin/clang++" COMPILER_FLAGS="-fsanitize=thread"
      compiler: clang
      addons: *stuff

before_install:
  - export CC="${CC_COMPILER}"
  - export CXX="${CXX_COMPILER}"
  - export ASAN_OPTIONS="symbolize=1"

install:
  - pip install --user flake8

before_script:
  # Check the style of a subset of Python code until the other code is updated.
  - flake8 ./scripts/*

script:
  - ./check.py --only-prepare
  - cmake . -DCMAKE_C_FLAGS="$COMPILER_FLAGS" -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS"
  - make -j2
  - ./check.py

notifications:
  email: false
